### ISSUE TITLE
Duplicated selectors

### ISSUE THREAD

**Issue by zachfedor** [Lazaro300x/more-css-practice#4]
https://github.com/Lazaro300x/more-css-practice/blob/b5fa37240f644be1a3b40652d22875a90a327ca3/airbnb/styles.css#L25-L50

Laz, you're making this harder on yourself than you need to. You made three rulesets that are exactly the same, but you can just make one and keep adding to the selectors if you want other things to have the same rules.

Also, you copied and pasted the `select` and `textarea` element selectors on every single one, meaning you're applying the same rules to each of these elements three separate times.

Why not keep it simple and do this? It selects *all* of your inputs, select boxes, and text areas at once.
```css
input, select, textarea { 
     width: 25%; 
     padding: 12px; 
     border: 1px solid #ccc; 
     border-radius: 4px; 
     margin-top: 6px; 
     margin-bottom: 16px; 
 } 
```
